baseURL = "ansgarkock.de"
languageCode = "de"
title = "Ansgar Leonard Kock"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "de"
enableEmoji = true
paginate = 5
enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
