[de]
contentDir = "content/de"
languageName = "Deutsch"
languageCode = "de"
weight = 1

[en]
contentDir = "content/en"
languageName = "English"    
languageCode = "en"
weight = 2

[pt-br]
contentDir = "content/pt-br"
languageName = "Português do Brasil"    
languageCode = "pt-br"
weight = 3
