navbar_title = 'Ansgar Leonard Kock'
footer = "<a href=\"/impressum/\">Impressum</a> | <a href=\"https://aac.unicode.org/sponsors#b03C0\">&#960;</a>"
author = "kaiiiz"
color_scheme = "light"

enable_zooming_js = true
enable_toc = true
enable_site_search = false
enable_math = false

# SEO
enable_open_graph = true
enable_twitter_cards = false

# Collapsible Menu
enable_collapsible_toc = false
enable_collapsible_changelogs = true

[list_layout]
enable_group_by_year = true
enable_show_date = true
enable_pagination = false

# syntax highlight settings
[syntax_highlight]
lib = "prism.js" # "builtin" | "prism.js"

    [syntax_highlight.builtin]
    enable_code_copy = true

    [syntax_highlight.prism]
    enable_code_copy = true
    enable_line_no = false
